### ISSUE TITLE
error: ProviderError: execution reverted: LibDiamondCut: Can't add function that already exists

### ISSUE THREAD

**Issue by InnoOkeke** [mudgen/diamond-1#10]
Hi guys,

I am currently working on the smart contract and get the following error when deploying the smart contract. 
error: ProviderError: execution reverted: LibDiamondCut: Can't add function that already exists

How do i resolve this?

thanks

**Comment by mudgen** [comment]
The is resolved by not trying to add functions to the diamond that have already been added to the diamond.  So modify your deployment code to not add the same functions to the diamond twice.

**Comment by InnoOkeke** [comment]
thanks mate
