### ISSUE TITLE
DiamondCutFacet.sol is NOT standard

### ISSUE THREAD

**Issue by fulldecent** [mudgen/diamond-1#3]
At https://github.com/mudgen/diamond-1/blob/1.3.5/contracts/facets/DiamondCutFacet.sol#L13

it is referred that this is the `// Standard diamondCut external function`.

But actually this is NOT standardized. The standard makes no mention that this function be restricted to OWNER usage.

**Comment by mudgen** [comment]
Thanks. I removed the comment.
