### ISSUE TITLE
Use explicit enum values

### ISSUE THREAD

**Issue by fulldecent** [mudgen/diamond-1#4]
At https://github.com/mudgen/diamond-1/blob/1.3.5/contracts/interfaces/IDiamondCut.sol#L10

When using Remix to deploy a contract, it does not have a cute way to type in all these Facet parameters.

So you are forced to type in like `[0x430781320498173409873, 1, [0x238974, 0x298374]]` to mean "Do a REPLACE operation on this contract with those two function selectors".

This relies one everybody knowing that ADD=0, REPLACE=1, REMOVE=2 and typing in that literal number above.

Experience could be improved if the enum explicitly documented those three enum case literals.

**Comment by mudgen** [comment]
Good idea. I'm adding this.  Thanks.

**Comment by mudgen** [comment]
This was done. Thanks.
