### ISSUE TITLE
Example deployment script

### ISSUE THREAD

**Issue by Walodja1987** [mudgen/diamond-1#6]
**Idea:** It would be great to have an example deployment script (e.g., truffle 2_deploy_contracts.js) that can be used in truffle. The script should take facet addresses as inputs, calculate the respective function selectors and create the array of structs to be passed to the diamond constructor.

**Comment by mudgen** [comment]
Yes, there is one here: https://github.com/mudgen/diamond-1/blob/master/migrations/2_diamond.js

**Comment by Walodja1987** [comment]
Many thanks!!

**Comment by mudgen** [comment]
Welcome!
