### ISSUE TITLE
Missing test contracts in 2_diamonds.js

### ISSUE THREAD

**Issue by Walodja1987** [mudgen/diamond-1#7]
In 2_diamonds.js, `const diamondCut` part, the test contracts seem to be missing. I would have expected to see the following two elements in the diamondCut array:

```
[Test1Facet.address, FacetCutAction.Add, getSelectors(Test1Facet)],
[Test2Facet.address, FacetCutAction.Add, getSelectors(Test2Facet)]
```

**Comment by mudgen** [comment]
Yes, the test contracts could be added that way.   In this case the test contracts are added in this this test script: https://github.com/mudgen/diamond-1/blob/master/test/diamondTest.js#L121
